In [11]:
from sklearn.preprocessing import StandardScaler
from seaborn import load_dataset
import pandas as pd 
tip_data = load_dataset('tips')
tip_data.head()
num_feats = tip_data[['total_bill', 'tip', 'size']]
std_scaler = StandardScaler()
num_std = std_scaler.fit_transform(num_feats)
num_std[:5]

array([[-0.31471131, -1.43994695, -0.60019263],
       [-1.06323531, -0.96920534,  0.45338292],
       [ 0.1377799 ,  0.36335554,  0.45338292],
       [ 0.4383151 ,  0.22575414, -0.60019263],
       [ 0.5407447 ,  0.4430195 ,  1.50695847]])

In [7]:
# The mean of each feature in the scaled data

std_scaler.mean_

array([19.78594262,  2.99827869,  2.56967213])

In [8]:
# Variance of the scaled features

std_scaler.var_

array([78.92813149,  1.90660851,  0.9008835 ])

In [9]:
#Scaled data has zero mean an unit variance.
import numpy as np

print(f'The mean of scaled data: {np.round(num_std.mean(axis=0))}')
print(f'The standard deviation of scaled data: {num_std.std(axis=0)}')

The mean of scaled data: [-0.  0. -0.]
The standard deviation of scaled data: [1. 1. 1.]


In [12]:
# Converting the scaled values back to datframe 

num_std_scaled_df = pd.DataFrame(num_std, columns=num_feats.columns)
num_std_scaled_df.head()

total_bill       tip      size
0   -0.314711 -1.439947 -0.600193
1   -1.063235 -0.969205  0.453383
2    0.137780  0.363356  0.453383
3    0.438315  0.225754 -0.600193
4    0.540745  0.443020  1.506958