In [3]:
import numpy as np
## Indexing 2D array
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
#Selecting individual element
#array_2d[row][column]
#let select 5 that is row 1 and column1 (we start from 0!!)
array_2d[1][1]

5

In [5]:
#Let select 9 that is row 2 column 2
array_2d[2][2]

9

In [7]:
#Selecting whole row
#array_2d[row]
array_2d[2]

array([7, 8, 9])

In [8]:
#Selecting group of elements in 2d array
#array[row, columns].. you select rows and columns

#let select the first two rows
#rows :2 denotes that we are selecting all rows up to the second
#columns: denotes that all columns are selected

array_2d[:2,:]


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#Selecting all first two rows and first two colums
array_2d[:2,0:2]

array([[1, 2],
       [4, 5]])

In [10]:
## This will return all rows, and so all columns and so same as orginal array
array_2d[0:3,:]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
## return the second row

array_2d[2,:]

array([7, 8, 9])

In [12]:
## return the second column

array_2d[:,2]

array([3, 6, 9])

In [13]:
## return the last two columns

array_2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [14]:
## return the first column

array_2d[:,0]

array([1, 4, 7])

In [15]:
## return the first row

array_2d[0,:]

array([1, 2, 3])

In [16]:
## return the first row

array_2d[0,:]

array([1, 2, 3])

In [17]:
## return the first column

array_2d[:,0]

array([1, 4, 7])