In [1]:
import numpy as np

In [2]:
#let create two arrays
arr1 = np.arange(0,5)
arr2 = np.arange(6,11)

In [3]:
#Addition
arr1 + arr2

array([ 6,  8, 10, 12, 14])

In [4]:
#Subtraction
arr2 - arr1

array([6, 6, 6, 6, 6])

In [5]:
#Multiplication
arr1 * arr2

array([ 0,  7, 16, 27, 40])

In [6]:
#Division
arr1 / arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [7]:
##Sqaring
arr1 ** 2

array([ 0,  1,  4,  9, 16])