In [2]:
import numpy as np
## Let's create an array

arr= np.array(([1,2,3],[4,5,6],[7,8,9]))

In [3]:
## Select all elements in an array which are less than 6

arr[arr <6 ]

array([1, 2, 3, 4, 5])

In [4]:
## Select all elements in an array which are greater than 6

arr[arr > 6]

array([7, 8, 9])

In [5]:
## Select all elements in an array which are greater than 6

arr[arr > 6]

array([7, 8, 9])

In [6]:
## Select all even numbers in an array

arr[arr % 2 ==0 ]

array([2, 4, 6, 8])

In [7]:
## Select all odd numbers in an array

arr[arr % 2 !=0 ]

array([1, 3, 5, 7, 9])

In [8]:
## You can also have multiple conditions

## In all odd numbers, return values which are greater or equal to 5


arr[(arr % 2 !=0 ) & (arr >=5) ]


array([5, 7, 9])

In [9]:
## Using logical selection, you can also return True for values in which a given condition is met in an array

arr > 5


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [10]:
## We do not have 0 in our array

arr == 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])